# Generated by Django 5.1.1 on 2024-09-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('org_name', models.TextField(primary_key=True, serialize=False)),
                ('org_type', models.TextField()),
                ('web_site', models.TextField()),
                ('director', models.TextField()),
                ('phone_number', models.TextField()),
                ('org_structure', models.TextField()),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
    ]
