# Generated by Django 5.1.1 on 2024-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='activity_type',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
